### ISSUE TITLE
Support for Next.js 7

### ISSUE THREAD

**Issue by ocean90** [ragingwind/next-workbox-webpack-plugin#8]
Next.js 7 changed the directory structure of `.next`, see https://nextjs.org/blog/next-7/#static-cdn-support. Due to the changes the precache-manifest is currently empty.

**Comment by beldar** [comment]
Please fix this otherwise this great plugin is useless

**Comment by ragingwind** [comment]
Sorry for inconvenience guys. I've not used Next.js anymore for a long time so I didn't catch up what changed. Please, make a PR and I will accept it and publish to npm

**Comment by ragingwind** [comment]
Now next9 support
